config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations"}
  get '/home' => 'static_pages#home'

  get '/about' => 'static_pages#about'

  delete '/pins' => 'pins#delete_all'

  delete '/users' => 'users#delete_all'

  delete '/boards' => 'boards#delete_all'

  root to: 'users#index'

  resources :boards

  resources :pins

  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>Pinterest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
      	<%= link_to "Pinterest", home_path %> 
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
        	<%= link_to "Users", users_path %>
        </li>
        <li>
        	<%= link_to "Pins", pins_path %>
        </li>
        <li>
        	<%= link_to "Boards", boards_path %>
        </li>
      </ul>

      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- <table>
<td class="navbar"><%= link_to "Users", users_path %></td>
<td class="navbar"><%= link_to "Pins", pins_path %></td>
<td class="navbar"><%= link_to "Boards", boards_path %></td>
<td class="navbar"><%= link_to "Home", home_path %></td>
<td class="navbar"><%= link_to "About", about_path %></td>
</table> -->

<%= yield %>

</body>
</html>